repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 4.0.0a1
  hooks:
  - id: sqlfluff-lint
  - id: sqlfluff-fix
