# --- Gateway Connection ---
gateways:
  live:
    connection:
      type: duckdb
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}.db"
    state_schema: sqlmesh
#  live:
#    connection:
#      type: snowflake
#      concurrent_tasks: 10
#      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
#      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
#      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
#      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
#      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
#      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
#    state_schema: sqlmesh

default_gateway: live

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: snowflake
  start: 2025-11-02 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
