# --- Gateway Connection ---
gateways:
  snowflake:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connection
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/snowflake/#connection-options
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      # concurrent_tasks: 4
      # register_comments: True
      # pre_ping: False
      # pretty_sql: False
      # schema_differ_overrides:
      # catalog_type_overrides:
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      # database:
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      # authenticator:
      # token:
      # host:
      # port:
      # application: Tobiko_SQLMesh
      # private_key:
      # private_key_path:
      # private_key_passphrase:
      # session_parameters:

default_gateway: snowflake

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: snowflake
  start: 2025-11-02 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
